SHOW DATABASES;
CREATE DATABASE DEMO2;
CREATE DATABASE SAMPLE3;
DROP DATABASE SAMPLE3;
SHOW DATABASES;
SHOW TABLES;
USE DEMO2;
CREATE TABLE PRASAD_COMPANY (
EMPLOYEEID VARCHAR(8),
EMPLOYEE_NAMES VARCHAR(10),
EMP_DESIGNATION VARCHAR(10),
EMP_AGE INT);
SHOW TABLES;
CREATE TABLE STUDENT (
ROLLNUMBER VARCHAR(10),
CITY VARCHAR (10),
PERCENTAGE VARCHAR (10),
AGE VARCHAR (10)
);
SHOW TABLES;
INSERT INTO STUDENT VALUES
('10','AURANGABAD','75%','23'),
('11','PUNE','80%','23'),
('12','JALNA','85%','23'),
('13','HYDERABAD','90%','23');
SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES
('15','AURANGABAD','80%','23');

SELECT * FROM STUDENT;

