SHOW DATABASES;
CREATE DATABASE DEMO2;
CREATE DATABASE SAMPLE3;
DROP DATABASE SAMPLE3;
SHOW DATABASES;
SHOW TABLES;
USE DEMO2;
CREATE TABLE PRASAD_COMPANY (
EMPLOYEEID VARCHAR(8),
EMPLOYEE_NAMES VARCHAR(10),
EMP_DESIGNATION VARCHAR(10),
EMP_AGE INT);
SHOW TABLES;