SHOW TABLES;
SHOW DATABASES;
USE SAMPLE2;
SHOW TABLES;
CREATE TABLE PG1(
ROOMNUM VARCHAR(10),
BED INT(10),
PEOPLE VARCHAR(10),
COMPANY VARCHAR(10)
);
SHOW TABLES;
DROP TABLE PG1;
SHOW TABLES;
INSERT INTO PG VALUES 
('A1','5','4','DEXIAN'),
('A2','4','4','ZS'),
('A3','5','6','TIAA'),
('A4','5','5','TCS');
SHOW TABLES;
SELECT * FROM PG;
CREATE TABLE CLASS(
STUDENTNAME VARCHAR(10),
SUBJECTS VARCHAR(10),
AVGAGE VARCHAR(10),
CITY VARCHAR(10)
);
SHOW TABLES;
SELECT * FROM CLASS;
INSERT INTO CLASS VALUES
('PRASAD','SANSKRIT','25','AURANGABAD'),
('VYANKATESH','HINDI','23','PARLI'),
('PRATHAMESH','ENGLISH','25','NANDED'),
('AKSHAY','MARATHI','25','AURANGABAD');
SELECT * FROM CLASS;
SELECT COUNT(*) AS DISTINCTCITY FROM (SELECT DISTINCT CITY FROM CLASS) AS DISTINCTCITY

